daq:
  IdelayStep: '8'
  NChips: '1'
  Number_of_events_per_readout: '-1'
  active_menu : 'randomL1A'
  
  elinks_daq:
    - { name : 'link0', polarity: 1, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 1 }
  elinks_trg:
    - { name : 'link0', polarity: 0, idcode: 0 }
    - { name : 'link1', polarity: 1, idcode: 2 }
    - { name : 'link2', polarity: 1, idcode: 3 }
    - { name : 'link3', polarity: 0, idcode: 1 }

  elinks_trg_phase: ##only needed when using external L1A source 
    - { name : 'link0', polarity: 1, idcode: 1 }
 

  zmqPushPull_port: '8888'
  delayScanData_port: '8889'
  menus:
    dummy:
      NEvents: 10000
      NEventsPerPush: 200
    #randomL1a:
    randomL1A:
      NEvents: 10000
      log2_rand_bx_period: 10
    randomL1AplusTPG:
      NEvents: 10000
      log2_rand_bx_period: 10
      bx_min: 45
      trg_fifo_latency: 3
    externalL1A:
      NEvents: 10000
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
      loopBack: true
      bxCalibExt: 10
      lengthCalibExt: 2
      prescale: 0
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      maxDelay: 512
      delayStep: 1
      idlePattern: '0XACCCCCCC'
      acquireLength: 1000
    marsRndL1A:
      log2_rand_bx_period: 10
      bx_min: 45
client:
  data_push_port: '8888'
  hw_type: TB
  outputDirectory: data
  run_type: default
  serverIP: tbtester1
  #run_num: 99999
roc_s0:
  sc:
    DigitalHalf:
      0: 
        L1Offset: 10
        Bx_offset: 2
        CalibrationSC: 1
      1: 
        L1Offset: 10
        Bx_offset: 2
        CalibrationSC: 1
    GlobalAnalog:
      0:
        Delay9: 3 #3
        Delay87: 3 #3
        Delay65: 3 #3
        Delay40: 2 #2
        Idac_inv: 6 # 4 default, 6
        Idac_tot: 6 # 4 default, 6
        Ref_pa_cm: 0 # 3 default, 0=150mV, 1=2=200mV, 3=250mV, 0
        ON_backup: 0 # 1 default: 0 = enable compensation with common mode channel
        ON_conv: 1 # '1': enable conveyor bias
        SelExtADC: 0 # 1 default, 0
        SelRisingEdge: 1
        Dacb_dynran: 3 # 3 default, 0
        Gain_conv: 8 #8 links
        Cd: 0 # 7 default, 4
        Cf_comp: 10 # 10 default, 1
        Cf: 10 # 10 default, 1
        Rf: 12 # 8 default
        Dacb_vbi_pa: 32 # 32 default
        Dacb_vb_conv: 6 # 6 default
      1:
        Delay9: 3 #3
        Delay87: 3 #3
        Delay65: 3 #3
        Delay40: 2 #2
        Idac_inv: 6 # 4 default, 6
        Idac_tot: 6 # 4 default, 6
        Ref_pa_cm: 0 # 3 default, 0=150mV, 1=2=200mV, 3=250mV,0
        ON_backup: 0 # 1 default, 0 = enable compensation with common mode channel
        ON_conv: 1 # '1': enable conveyor bias
        SelExtADC: 0 # 1 default, 0 before
        SelRisingEdge: 1
        Dacb_dynran: 3 # 3 default, 0
        Gain_conv: 8 #8 rechts
        Cd: 0 # 7 default
        Cf_comp: 10 # 10 default
        Cf: 10 # 10 default
        Rf: 12 # 8 default
        Dacb_vbi_pa: 32 # 32 default
        Dacb_vb_conv: 6 # 6 default
    ReferenceVoltage:
      0:
        Vbg_1v: 3 # 5 default, 3
        Refi: 1 # 3 default, 1
        choice_cinj: 0 # O default
        cmd_120p: 0 # 0 default
        Calib_2V5: 0 
        Inv_vref: 550 #was 550, def 256
        Noinv_vref: 850 #was 850, def 316
        Tot_vref: 600 # was 678   500, 1000
        Toa_vref: 450 # was 200   200, 1000
      1:
        Vbg_1v: 3 # 5 default, 3
        Refi: 1 # 3 default, 1
        choice_cinj: 0 # O default
        cmd_120p: 0 # 0 default
        Calib_2V5: 0 
        Inv_vref: 550 #was 550, def 256
        Noinv_vref: 850 #was 850, def 316
        Tot_vref: 600 # was 678    500, 1000
        Toa_vref: 450 # was 200   200, 1000
    MasterTdc: 
      all:
        BIAS_I_CTDC_D: 10 # 24 by default
        FOLLOWER_CTDC_EN: 1 # 1 by default
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1 # 0 by default
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4 # 0 by default
        GLOBAL_EN_BUFFER_CTDC: 1 # 0 by default
        BIAS_CAL_DAC_CTDC_P_EN: 1 # 0 by default
        BIAS_CAL_DAC_CTDC_P_D: 2 # 0 by default
        BIAS_I_FTDC_D: 10 # 24 by default
        FOLLOWER_FTDC_EN: 1 # 1 by default
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1 # 0 by default
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4 # 0 by default
        GLOBAL_EN_BUFFER_FTDC: 1 # 0 by default
        CTDC_CALIB_FREQUENCY: 2 # 2 by default
        FTDC_CALIB_FREQUENCY: 2 # 2 by default
      #0:
        #CTRL_IN_REF_CTDC_P_D: 25 # 0 by default
        #CTRL_IN_REF_CTDC_P_EN: 1 # 0 by default
      #1: 
        #CTRL_IN_REF_CTDC_P_D: 15 # 0 by default
        #CTRL_IN_REF_CTDC_P_EN: 1 # 0 by default
    Top:
      all:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
    ch:
      all:
        Gain_conv: 4
        Inputdac: 31
        sign_dac: 0
        dacb: 0
    cm:
      all:
        Gain_conv: 4
        dacb: 0 # was 0
        sign_dac: 0
        Inputdac: 0
    calib:
      all:
        Gain_conv: 4
        dacb: 10 # was 0
        sign_dac: 0
        Inputdac: 31
